### ISSUE TITLE
Chapter 3 - docker-compose

### ISSUE THREAD

**Issue by timetobehappy** [arun-gupta/docker-for-java#1]
I am trying docker-compose up -d using the below and the container exits as it is not able to create a directory called deployment. 

``````````````````````````````````
version: '3'
services:
  web:
    image: jboss/wildfly
    volumes:
      - ~/deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8080:8080
````````````````````````````````````````

Error seen in logs: **/opt/jboss/wildfly/standalone/deployments is not writable** 

I am running on an AWS centos instance as user centos

[centos@ip-10.ec2.internal helloweb]$ hostnamectl
   Static hostname: ip-10.ec2.internal
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 
           Boot ID: 
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-514.6.2.el7.x86_64
      Architecture: x86-64
[centos@ip-10.ec2.internal helloweb]$
